# Generated by Django 4.1.2 on 2023-10-31 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название команды')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('logo', models.ImageField(max_length=50, upload_to='media/', verbose_name='Логотип Команды')),
                ('goals', models.IntegerField(blank=True, null=True, verbose_name='Голы')),
                ('coals_conceded', models.IntegerField(blank=True, null=True, verbose_name='Пропущенные голы')),
                ('possession', models.IntegerField(blank=True, null=True, verbose_name='Владение мячом')),
                ('passings_accuracy', models.IntegerField(blank=True, null=True, verbose_name='Точность передач')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.league')),
            ],
            options={
                'verbose_name': 'Информация о команде',
                'verbose_name_plural': 'Информация о командах',
            },
        ),
        migrations.CreateModel(
            name='WinnersEurope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('total_wins', models.IntegerField(blank=True, null=True, verbose_name='Всего побед')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams')),
            ],
            options={
                'verbose_name': 'Победители Лиги Европы',
                'verbose_name_plural': 'Победители Лиги Европы',
            },
        ),
        migrations.CreateModel(
            name='WinnersChampions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('total_wins', models.IntegerField(blank=True, null=True, verbose_name='Всего побед')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams')),
            ],
            options={
                'verbose_name': 'Победители Лиги Чемпионов',
                'verbose_name_plural': 'Победители Лиги Чемпионов',
            },
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('date', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams')),
            ],
            options={
                'verbose_name': 'Информация о тренере',
                'verbose_name_plural': 'Информация о тренерах',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('date', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('matched_played', models.IntegerField(blank=True, null=True, verbose_name='Сыгранные матчи')),
                ('minutes_played', models.IntegerField(blank=True, null=True, verbose_name='Минуты на поле')),
                ('goals', models.IntegerField(blank=True, null=True, verbose_name='Голы')),
                ('assists', models.IntegerField(blank=True, null=True, verbose_name='Голевые передачи')),
                ('yellow_cards', models.IntegerField(blank=True, null=True, verbose_name='Желтые карточки')),
                ('red_cards', models.IntegerField(blank=True, null=True, verbose_name='Красные карточки')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams')),
            ],
            options={
                'verbose_name': 'Информация о футболисте',
                'verbose_name_plural': 'Информация о футболистах',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения матча')),
                ('stage', models.CharField(max_length=50, verbose_name='Этап')),
                ('goals1', models.IntegerField(blank=True, null=True, verbose_name='Голы')),
                ('goals2', models.IntegerField(blank=True, null=True, verbose_name='Голы')),
                ('possession1', models.IntegerField(blank=True, null=True, verbose_name='Владение мячом')),
                ('possession2', models.IntegerField(blank=True, null=True, verbose_name='Владение мячом')),
                ('total_attempts1', models.IntegerField(blank=True, null=True, verbose_name='Всего ударов')),
                ('total_attempts2', models.IntegerField(blank=True, null=True, verbose_name='Всего ударов')),
                ('attack1', models.IntegerField(blank=True, null=True, verbose_name='Атаки')),
                ('attack2', models.IntegerField(blank=True, null=True, verbose_name='Атаки')),
                ('corners1', models.IntegerField(blank=True, null=True, verbose_name='Угловые')),
                ('corners2', models.IntegerField(blank=True, null=True, verbose_name='Угловые')),
                ('passings_accuracy1', models.IntegerField(blank=True, null=True, verbose_name='Точность передач')),
                ('passings_accuracy2', models.IntegerField(blank=True, null=True, verbose_name='Точность передач')),
                ('passes_completed1', models.IntegerField(blank=True, null=True, verbose_name='Точные передачи')),
                ('passes_completed2', models.IntegerField(blank=True, null=True, verbose_name='Точные передачи')),
                ('offsides1', models.IntegerField(blank=True, null=True, verbose_name='Офсайды')),
                ('offsides2', models.IntegerField(blank=True, null=True, verbose_name='Офсайды')),
                ('yellow_cards1', models.IntegerField(blank=True, null=True, verbose_name='Желтые карточки')),
                ('yellow_cards2', models.IntegerField(blank=True, null=True, verbose_name='Желтые карточки')),
                ('red_cards1', models.IntegerField(blank=True, null=True, verbose_name='Красные карточки')),
                ('red_cards2', models.IntegerField(blank=True, null=True, verbose_name='Красные карточки')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.league')),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name1', to='main.teams')),
                ('name2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name2', to='main.teams')),
            ],
            options={
                'verbose_name': 'Информация о матче',
                'verbose_name_plural': 'Информация о матчах',
            },
        ),
    ]
