# Generated by Django 4.1.2 on 2023-10-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'Лига', 'verbose_name_plural': 'Лиги'},
        ),
        migrations.AddField(
            model_name='league',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название лиги'),
        ),
    ]
