# Generated by Django 4.1.2 on 2023-11-01 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_league_options_league_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.league'),
        ),
    ]
