# Generated by Django 4.1.2 on 2023-11-01 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_teams_league'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='coals_conceded',
            new_name='goals_conceded',
        ),
    ]
