# Generated by Django 4.1.2 on 2023-11-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_coals_conceded_teams_goals_conceded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='passings_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='Точность передач'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='possession',
            field=models.FloatField(blank=True, null=True, verbose_name='Владение мячом'),
        ),
    ]
