# Generated by Django 4.1.2 on 2023-11-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_teams_passings_accuracy_alter_teams_possession'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='balls_recovered',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отборы'),
        ),
        migrations.AddField(
            model_name='teams',
            name='clean_sheets',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сухие матчи'),
        ),
        migrations.AddField(
            model_name='teams',
            name='distance_covered',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пройденное расстояние'),
        ),
        migrations.AddField(
            model_name='teams',
            name='red_cards',
            field=models.IntegerField(blank=True, null=True, verbose_name='Красные карточки'),
        ),
        migrations.AddField(
            model_name='teams',
            name='saves',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сэйвы'),
        ),
        migrations.AddField(
            model_name='teams',
            name='tackles_won',
            field=models.IntegerField(blank=True, null=True, verbose_name='Взятия мяча'),
        ),
        migrations.AddField(
            model_name='teams',
            name='yellow_cards',
            field=models.IntegerField(blank=True, null=True, verbose_name='Желтые карточки'),
        ),
    ]
