# Generated by Django 4.1.2 on 2023-11-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_teams_balls_recovered_teams_clean_sheets_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trener',
            new_name='Coach',
        ),
        migrations.RemoveField(
            model_name='players',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='players',
            name='date',
        ),
        migrations.RemoveField(
            model_name='players',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='players',
            name='minutes_played',
        ),
        migrations.RemoveField(
            model_name='players',
            name='red_cards',
        ),
        migrations.RemoveField(
            model_name='players',
            name='yellow_cards',
        ),
        migrations.AddField(
            model_name='players',
            name='age',
            field=models.DateField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='players',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Национальность'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='distance_covered',
            field=models.FloatField(blank=True, null=True, verbose_name='Пройденное расстояние'),
        ),
    ]
