# Generated by Django 4.1.2 on 2023-11-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_trener_coach_remove_players_assists_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Players',
        ),
    ]
