# Generated by Django 4.1.2 on 2023-11-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_players_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='matches_played',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сыгранные матчи'),
        ),
    ]
