# Generated by Django 4.1.2 on 2023-11-01 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_players_matches_played'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Players',
        ),
    ]
