# Generated by Django 4.1.2 on 2023-11-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Players',
        ),
    ]
