# Generated by Django 4.1.2 on 2023-11-01 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Национальность')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('matches_played', models.CharField(blank=True, max_length=50, null=True, verbose_name='Сыгранные матчи')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams')),
            ],
            options={
                'verbose_name': 'Информация о футболисте',
                'verbose_name_plural': 'Информация о футболистах',
            },
        ),
    ]
