# Generated by Django 4.1.2 on 2023-11-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='date',
        ),
    ]
