# Generated by Django 4.1.7 on 2023-11-19 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_healthinshurance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoinshurance',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthinshurance',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyinshurance',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
