# Generated by Django 4.1.7 on 2023-11-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_autoinshurance_client_healthinshurance_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinshurance',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='healthinshurance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='healthinshurance',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='healthinshurance',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='healthinshurance',
            name='surname',
        ),
    ]
