# Generated by Django 4.1.7 on 2023-11-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_healthinshurance_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinshurance',
            name='passport',
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
