# Generated by Django 4.1.7 on 2023-11-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_healthinshurance_passport_user_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoinshurance',
            name='type',
            field=models.CharField(blank=True, default='Автостраховка', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='healthinshurance',
            name='type',
            field=models.CharField(blank=True, default='Медицинская страховка', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertyinshurance',
            name='type',
            field=models.CharField(blank=True, default='Имущественная страховка', editable=False, max_length=100, null=True),
        ),
    ]
