# Generated by Django 4.1.7 on 2023-11-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_autoinshurance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoinshurance',
            name='type',
            field=models.CharField(blank=True, default='Автостраховка', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='healthinshurance',
            name='type',
            field=models.CharField(blank=True, default='Медицинская страховка', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertyinshurance',
            name='type',
            field=models.CharField(blank=True, default='Имущественная страховка', max_length=100, null=True),
        ),
    ]
