# Generated by Django 5.0 on 2023-12-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_autoinshurance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
    ]
