# Generated by Django 5.0 on 2023-12-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_date_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
