# Generated by Django 5.0 on 2023-12-06 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_student_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.program', verbose_name='Программа'),
        ),
    ]
