# Generated by Django 5.0 on 2023-12-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_group_name_alter_group_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='79241235678', max_length=100, null=True, verbose_name='Телефон'),
        ),
    ]
