# Generated by Django 5.0 on 2023-12-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='examiner',
        ),
        migrations.AddField(
            model_name='exam',
            name='examiner_first_name',
            field=models.CharField(blank=True, default='Иван', max_length=100, null=True, verbose_name='Имя экзаменатора'),
        ),
        migrations.AddField(
            model_name='exam',
            name='examiner_last_name',
            field=models.CharField(blank=True, default='Иванов', max_length=100, null=True, verbose_name='Фамилия экзаменатора'),
        ),
        migrations.AddField(
            model_name='exam',
            name='examiner_middle_name',
            field=models.CharField(blank=True, default='Иванович', max_length=100, null=True, verbose_name='Отчество экзаменатора'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, default='79241235325', max_length=100, null=True, verbose_name='Телефон'),
        ),
        migrations.DeleteModel(
            name='Examiner',
        ),
    ]
