# Generated by Django 5.0 on 2023-12-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_exam_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Фото'),
        ),
    ]
