# Generated by Django 5.0 on 2023-12-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
