# Generated by Django 5.0 on 2023-12-08 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инструктор'),
        ),
    ]
