# Generated by Django 4.1.2 on 2022-12-18 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите номер', max_length=50, verbose_name='Номер')),
                ('cost', models.IntegerField(help_text='Введите стоимость', verbose_name='Стоимость')),
                ('size', models.IntegerField(help_text='Введите размер', verbose_name='Размер')),
                ('count_people', models.IntegerField(help_text='Введите количество человек', verbose_name='Количество человек')),
                ('count_rooms', models.IntegerField(help_text='Введите количество комнат', verbose_name='Количество комнат')),
                ('count_beds', models.IntegerField(help_text='Введите количество кроватей', verbose_name='Количество кроватей')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название услуги', max_length=50, verbose_name='Название услуги')),
            ],
        ),
        migrations.CreateModel(
            name='SostavUslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nomer', models.ForeignKey(help_text='Выберите номер', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nomer', verbose_name='Номер')),
                ('id_uslugi', models.ForeignKey(help_text='Выберите услугу', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.uslugi', verbose_name='Услуга')),
            ],
        ),
        migrations.CreateModel(
            name='Gostinitsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название гостиницы', max_length=50, verbose_name='Название гостиницы')),
                ('status', models.BooleanField(default=False, help_text='Введите статус', verbose_name='Статус')),
                ('id_nomer', models.ForeignKey(help_text='Выберите номер', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nomer', verbose_name='Номер')),
            ],
        ),
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(help_text='Введите дату начала', verbose_name='Дата начала')),
                ('date_end', models.DateField(help_text='Введите дату конца', verbose_name='Дата конца')),
                ('id_nomer', models.ForeignKey(help_text='Выберите номер', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nomer', verbose_name='Номер')),
                ('id_user', models.ForeignKey(help_text='Выберите пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
