# Generated by Django 4.1.2 on 2022-12-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomer',
            name='photo_mini',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Фото мини'),
        ),
    ]
