# Generated by Django 4.1.2 on 2022-12-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_nomer_photo_mini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gostinitsa',
            name='status',
            field=models.BooleanField(default=False, help_text='Введите статус', verbose_name='Занят ли номер'),
        ),
    ]
