# Generated by Django 4.1.2 on 2022-12-18 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_gostinitsa_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gostinitsa',
            name='name',
        ),
    ]
