# Generated by Django 4.1.2 on 2022-12-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_gostinitsa_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bron',
            name='cost',
            field=models.IntegerField(default=0, help_text='Введите стоимость', verbose_name='Стоимость'),
        ),
    ]
