# Generated by Django 4.1.2 on 2022-12-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bron_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomer',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание', null=True, verbose_name='Описание'),
        ),
    ]
