# Generated by Django 4.1.2 on 2022-12-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bron_status_delete_gostinitsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bron',
            name='status',
            field=models.BooleanField(default=False, help_text='Введите статус', verbose_name='Занят ли номер'),
        ),
    ]
