# Generated by Django 4.1.2 on 2022-12-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_bron_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bron',
            name='status',
        ),
        migrations.AddField(
            model_name='nomer',
            name='status',
            field=models.BooleanField(default=False, help_text='Введите статус', verbose_name='Статус'),
        ),
    ]
