# Generated by Django 4.1.2 on 2022-12-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_bron_status_nomer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bron',
            name='status',
            field=models.BooleanField(default=False, help_text='Введите статус', verbose_name='Статус'),
        ),
    ]
