# Generated by Django 4.1.2 on 2022-12-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bron_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bron',
            name='status',
        ),
    ]
