# Generated by Django 4.1.2 on 2022-12-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clients_materials_positions_types_of_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='st',
            field=models.BooleanField(default=False, help_text='Является ли сотрудником', verbose_name='Сотрудник'),
        ),
    ]
