# Generated by Django 4.1.2 on 2022-12-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_users_st'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='st',
        ),
    ]
