# Generated by Django 4.1.2 on 2022-12-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_users_st'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='kl',
            field=models.BooleanField(default=False, help_text='Сотрудник или клиент', verbose_name='Клиент'),
        ),
    ]
