# Generated by Django 4.1.2 on 2022-12-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_orders_user_types_of_services_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='types_of_services',
            name='prewiev',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Фото'),
        ),
    ]
