# Generated by Django 4.1.2 on 2022-12-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_types_of_services_prewiev_alter_users_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='cost',
            field=models.IntegerField(blank=True, help_text='Введите стоимость', null=True, verbose_name='Стоимость'),
        ),
    ]
