# Generated by Django 4.1.2 on 2022-12-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_materials_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата покупки'),
        ),
    ]
