# Generated by Django 4.1.2 on 2022-12-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_purchases_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
