# Generated by Django 4.1.2 on 2022-12-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cashier',
            field=models.BooleanField(default=False, verbose_name='Кассир'),
        ),
        migrations.AddField(
            model_name='user',
            name='warehouse_manager',
            field=models.BooleanField(default=False, verbose_name='Менеджер склада'),
        ),
    ]
