# Generated by Django 4.1.2 on 2022-12-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_cashier_user_warehouse_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, help_text='Введите отчество', max_length=50, null=True, verbose_name='Отчество'),
        ),
    ]
