# Generated by Django 4.1.2 on 2022-12-12 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_manufacturers_materials_shops_subtypes_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='city',
            field=models.CharField(blank=True, help_text='Введите город', max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='house',
            field=models.CharField(blank=True, help_text='Введите дом', max_length=50, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='phone',
            field=models.CharField(blank=True, help_text='Введите телефон', max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='street',
            field=models.CharField(blank=True, help_text='Введите улицу', max_length=50, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='price',
            field=models.IntegerField(help_text='Введите цену', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='price_delivery',
            field=models.IntegerField(blank=True, help_text='Введите цену доставки', null=True, verbose_name='Цена доставки'),
        ),
        migrations.RemoveField(
            model_name='materials',
            name='types',
        ),
        migrations.AlterField(
            model_name='materials',
            name='unit_of_measurement',
            field=models.CharField(blank=True, help_text='Введите единицу измерения', max_length=50, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(blank=True, help_text='Введите дату', null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Выберите магазин', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shops', verbose_name='Магазин'),
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sostav_prodazhi',
        ),
        migrations.AlterField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Выберите пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='city',
            field=models.CharField(blank=True, help_text='Введите город', max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='house',
            field=models.CharField(blank=True, help_text='Введите дом', max_length=50, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='street',
            field=models.CharField(blank=True, help_text='Введите улицу', max_length=50, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='sostav_prodazhi',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Выберите материал', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.materials', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='sostav_prodazhi',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Введите количество', null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='sostav_prodazhi',
            name='total_cost',
            field=models.IntegerField(blank=True, default=0, help_text='Введите стоимость', null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='subtypes',
            name='name',
            field=models.CharField(blank=True, help_text='Введите подтип', max_length=50, null=True, unique=True, verbose_name='Подтип'),
        ),
        migrations.RemoveField(
            model_name='types',
            name='subtypes',
        ),
        migrations.AddField(
            model_name='materials',
            name='types',
            field=models.ForeignKey(blank=True, help_text='Выберите тип', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.types', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='sales',
            name='sostav_prodazhi',
            field=models.ForeignKey(blank=True, help_text='Выберите состав продажи', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sostav_prodazhi', verbose_name='Состав продажи'),
        ),
        migrations.AddField(
            model_name='types',
            name='subtypes',
            field=models.ForeignKey(blank=True, help_text='Выберите подтип', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subtypes', verbose_name='Подтип'),
        ),
    ]
