# Generated by Django 4.1.2 on 2022-12-13 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_sales_total_cost_alter_manufacturers_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='types',
        ),
        migrations.RemoveField(
            model_name='types',
            name='subtypes',
        ),
        migrations.CreateModel(
            name='Subtype_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.ForeignKey(help_text='Выберите подтип', on_delete=django.db.models.deletion.CASCADE, to='main.subtypes', verbose_name='Тип')),
                ('type', models.ForeignKey(help_text='Выберите тип', on_delete=django.db.models.deletion.CASCADE, to='main.types', verbose_name='Тип')),
            ],
        ),
        migrations.AddField(
            model_name='materials',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Выберите тип', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subtype_type', verbose_name='Тип'),
        ),
    ]
