# Generated by Django 4.1.2 on 2022-12-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_materials_types_remove_types_subtypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
