# Generated by Django 4.1.2 on 2022-12-13 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_materials_photo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Введите количество', null=True, verbose_name='Количество')),
                ('total_cost', models.IntegerField(blank=True, default=0, help_text='Введите стоимость', null=True, verbose_name='Стоимость')),
                ('material', models.ForeignKey(blank=True, help_text='Выберите материал', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.materials', verbose_name='Материал')),
                ('user', models.ForeignKey(blank=True, help_text='Выберите пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
