# Generated by Django 4.1.2 on 2022-12-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='materials',
            name='in_stock',
            field=models.IntegerField(blank=True, help_text='Введите количество на складе', null=True, verbose_name='Количество на складе'),
        ),
    ]
