# Generated by Django 4.1.2 on 2022-12-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_materials_description_materials_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='shop',
        ),
        migrations.AddField(
            model_name='sales',
            name='total_cost',
            field=models.IntegerField(blank=True, default=0, help_text='Введите стоимость', null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sostav_prodazhi',
            field=models.CharField(blank=True, help_text='Выберите состав продажи', max_length=250, null=True, verbose_name='Состав продажи'),
        ),
    ]
