# Generated by Django 4.1.2 on 2022-12-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_sales_shop_sales_total_cost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sostav_prodazhi',
        ),
    ]
